name: Link checker

on: push

#env:
#  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
jobs:
  build:
    name: Build and Test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: 'mlc_config.json'
          folder-path: 'docs' # comma separated
          max-depth: 2
          # check-modified-files-only: ${{ github.event_name == 'pull_request' && 'yes' || 'no' }}
          base-branch: main
